# Generated by Django 5.2.8 on 2026-06-27 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_incidenciaexamen_perfilbiometrico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='id_profesor',
        ),
        migrations.AddField(
            model_name='examen',
            name='id_profesor',
            field=models.ForeignKey(blank=True, help_text='Profesor autor de este examen', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
