# Generated by Django 5.2.8 on 2026-06-27 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_remove_cursos_id_profesor_examen_id_profesor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id_aula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_aula', models.CharField(help_text='Ej: Pabellón A - 101, Laboratorio 3', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'aula',
            },
        ),
        migrations.AlterField(
            model_name='salon',
            name='id_profesor',
            field=models.ForeignKey(db_column='id_profesor', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='salones_gestionados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salon',
            name='nombre_salon',
            field=models.CharField(help_text='Nombre de la sección o grupo', max_length=100),
        ),
        migrations.AddField(
            model_name='salon',
            name='aula_fisica',
            field=models.ForeignKey(blank=True, help_text='Aula física donde se dicta la clase', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.aula'),
        ),
    ]
